# Remedies to Questionable Research Practices {#remedies}

Remedies, countermeasures, and other ways to prevent questionable research practices. The remedies are ordered from small to large: from what an individual can do volontarily, all the way up to what research institutions and governments can mandate.

<!--
How to write each remedy
------------------------
1. Short definition
2. More detailed description: what it does, why, etc.
3. What it counteracts and how
-->

## 21 word solution

@simmons_21_2012 [p. 1] suggested using the following sentence in the methods section:

> We report how we determined our sample size, all data exclusions (if any), all manipulations, and all measures in the study.

If the sample size is not determined in advance, for example, you could write something like this:

> We added 50 observations after analyzing the first 100.

## Thinking about biases {#metacognition}

Also known as: *metacognition*

@greenland_need_2017 suggested that we need to bring cognitive psychology into methodology.

## Change significance threshold {#change-alpha}

In the social sciences, it is common to use p < .05 as a threshold for statistical significance (what counts as a discovery or positive result). This means that we allow 5 percent false positives by chance alone, on average. In combination with publication bias and questionable research practices, the false positive rate is actually much higher.

However, several has suggested that researchers should lower the significance threshold to p < .005 [@benjamin_redefine_2018].

Others have responded that researchers should instead justify what threshold they use [@lakens_justify_2018].

## Blind analysis {#blind-analysis}

Blind analysis means removing any identifying information before the analysis, and only to add them back again once the analysis is done.

The goal of blind analysis is to remove any unintentional biases that might occur, such as rerunning the analysis in a different way when the results are not in the preferred direction.

## Open data {#open-data}

Open data means making the data, materials and other research material openly accessible for anyone. This makes it possbile for others to verify the data and conclusions derived from the data. Open data also makes it possible to help identify fraud, cherry-picking, and more.

However, some data are sensitive. There are several tools that can help you:

- [synthpop](https://synthpop.org.uk/) - generates a synthetic version of individual-level data. Available as an R package.
- [semproducible](https://github.com/peterdalle/semproducible) - turns a lavaan model into reproducible code without disclosing the raw data. Just can then paste the code in the appendix of a journal article. Available as an R package.

If you make your data open, it is important to give the data an open license that states what others can and cannot do with the data.

The abbreviation *FAIR* is sometimes used in relation to research data, which stands for findability, accessibility, interoperability, and reusability. You can read more at <https://en.wikipedia.org/wiki/FAIR_data>.

## Preprint {#preprint}

A preprint is a research paper that is made available before the paper is reviewed or published in a journal. The preprint can be published in one of the numerous [preprint servers](#resources) that exists online.

Preprints counteract [publication bias](#publication-bias) because negative findings can be published.

## Preregistration {#preregistration}

## Replication {#replication}

## Registered report {#registered-report}

 A registered report is a journal article format with peer review before results are known. Registered reports are conduccted in two stages.
 
 1. In the first stage you write a journal article with introduction and methods section and send it to the journal for peer review. The reviewers give feedback on the introduction and feasability of the method. If the paper is accepted then it is accepted *regardless* of what the results will show. You then carry out the data collection and analyze the results.
 2. In the second stage you send the full article, including results and discussion section, to the journal. The reviewers then compare whether you did what you intended to do, and whether the conclusions follow from the data. The reviewers cannot object to the results at this stage because they have already agreed to the study design.

Registered reports counteract [publication bias](#publication-bias) because it is not unexpected results that determine publication, but study rationale and study design.

## Post publication peer review {#post-publication-peer-review}

## Adversarial collaboration

Also known as: *red team/blue team*

Two or more scientists with opposing views work together. 

The goal of adversarial collaboration is to design a study that satisfies both sides of the debate, and that there are no obvious biases or weaknesses in the design of the study.

## Changed incentives

## Supervisors

Supervisors "have an important function in shaping students’ attitudes towards QRPs" [@krishna_questionable_2018, 1].

## Education

Education in open science and ethical research is another way to remedy questionable research practices.

## Research Culture

- **Being able to speak up against**.
- **Scientific integrity**.
- **Quality over quantity**.

## Summary {#remedies-summary}
