# (APPENDIX) Appendix {-}

# Resources and tools {- #resources}

Free resources and free tools to help you make better research.

Resource | Description
----------- | ----------------------------
[FORRT](https://forrt.org/) | Framework for Open and Reproducible Research Training that aimes to integrate open and reproducible science into higher education
[Social Science Prediction Platform](https://socialscienceprediction.org) | Help predict research results
[OSF projects](https://osf.io/) | Upload your research data to Open Science Framework (OSF) for long-term storage
[Zenodo](https://zenodo.org/) | Upload your research data to Zenodo for long-term storage
[OSF preprints](https://osf.io/preprints) | Publish preprints of your papers before you send them to journals
[OSF preregistration](https://osf.io/prereg) | Preregister your study at Open Science Framework (OSF)
[Registered reports](https://www.cos.io/initiatives/registered-reports) | Find journals that offers [registered reports](#registered-report): peer review before results are known
[Top Factor](https://www.topfactor.org/) | Find journals that value good research
[Glossary](https://forrt.org/glossary/) | Glossary of terms relating to open scholarship
[The Open Science Training Handbook](https://open-science-training-handbook.gitbook.io/book/) | A book about how to spread open science principles
[PubPeer](https://pubpeer.com/) | Online platform for post-publication peer review

## Open textbooks

- [Improving Your Statistical Inferences](https://lakens.github.io/statistical_inferences/) By Daniël Lakens 

## Networks in different countries

- [Open Scholarship Grassroots Community Networks](https://docs.google.com/spreadsheets/d/1LNF5_bOkRV-RLIF4HYmu-gOemIa4IdfXEer89fM-Vy8/edit#gid=0)
